### ISSUE TITLE
必须公司开启及速打卡才可以

### ISSUE THREAD

**Issue by sunqingquan** [ZhipingYang/dingtalk_check_in#2]
利用的是钉钉的非人脸识别的极速打卡功能，但是如果公司没有开通极速打卡就不行了

**Comment by ZhipingYang** [comment]
这样啊。sorry啊，我以为自动打卡都是自己开关的。设置里面有

**Comment by niguangxingzou** [comment]
幸好我找到了一个另外的方法来永久代替，再也不用担心钉钉升级了，微信，陌陌，微博，各种定位通吃。真兴奋呢。

**Comment by ZhipingYang** [comment]
@niguangxingzou 写死的定位会影响到手机的正常使用，还需要重启清除定点定位。不过不失为一个好法子
