### ISSUE TITLE
开一晚上感觉很傻

### ISSUE THREAD

**Issue by Tonyhe666** [ZhipingYang/dingtalk_check_in#7]
为什么不写在后台运行呢？

**Comment by ZhipingYang** [comment]
那就需要苹果越狱了，才可以的操作

**Comment by Tonyhe666** [comment]
iOS也可以后台可以一直跑timer，能不能在timer里做一些事情呢？

**Comment by Tonyhe666** [comment]
> 那就需要苹果越狱了，才可以的操作

iOS也可以后台可以一直跑timer，能不能在timer里做一些事情呢？你这关闭issue也太快了

**Comment by ZhipingYang** [comment]
后台？？锁屏下就是不能唤起其他APP啊，所以不越狱只有代码注入或者物理外挂打卡了。目前没有想到好的方法

**Comment by Tonyhe666** [comment]
好吧，我想的有点简单了！以为后台可以执行代码就能打开其他app
